### ISSUE TITLE
Getting an data type error while running the code

### ISSUE THREAD

**Issue by Mohammadkhan18** [IMMORTALCHIRU/Autism-Spectrum-Disorder#1]
when im running the streamlit run app.py it is showing me this error 

![ERROR](https://github.com/IMMORTALCHIRU/Autism-Spectrum-Disorder/assets/95682232/65e6c872-d60e-4d52-a767-c1e661a3b47d)

i have given a proper path to the train_model.sav and without this pickle part the code is working fine but can't able to predict without puickle.open() method

**Comment by IMMORTALCHIRU** [comment]
> when im running the streamlit run app.py it is showing me this error
> 
> ![ERROR](https://private-user-images.githubusercontent.com/95682232/331153512-65e6c872-d60e-4d52-a767-c1e661a3b47d.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjAyOTksIm5iZiI6MTcxNTg1OTk5OSwicGF0aCI6Ii85NTY4MjIzMi8zMzExNTM1MTItNjVlNmM4NzItZDYwZS00ZDUyLWE3NjctYzFlNjYxYTNiNDdkLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDExNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NDE1MzMwMmEwYWM3ODdlZTQ3Yzc5OWQyYTk5ZmExNDE3N2NmMDhhZTBkODUxY2U2ZDdiZjc3MWQ3NWIyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0bgEazs--ZxRAT4kRgbiw0TUcTs-ZOTV2g4xUry_WI)
> 
> i have given a proper path to the train_model.sav and without this pickle part the code is working fine but can't able to predict without puickle.open() method

**As i mentioned please use the python 3.6.8 interpreter and then try to install ```pip install scikit-learn ``` It will resolve the problem.**
