### ISSUE TITLE
Getting this error while installing streamlit

### ISSUE THREAD

**Issue by Mohammadkhan18** [IMMORTALCHIRU/Autism-Spectrum-Disorder#2]
As you have mention i did install python 3.6.8

but when i try to install streamlit im getting this error : 
 
 Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\program files\python36\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-m7s36mdy\\pywinpty\
\setup.py'

this error is not come when i try t nstall streamlit in my latest python version

**Comment by IMMORTALCHIRU** [comment]
> As you have mention i did install python 3.6.8
> 
> but when i try to install streamlit im getting this error :
> 
> Complete output from command python setup.py egg_info: Traceback (most recent call last): File "", line 1, in File "c:\program files\python36\lib\tokenize.py", line 452, in open buffer = _builtin_open(filename, 'rb') FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Admin\AppData\Local\Temp\pip-install-m7s36mdy\pywinpty \setup.py'
> 
> this error is not come when i try t nstall streamlit in my latest python version

My code is working properly without any errors fews days back itself i have installed it in my clients laptop, so please do check the installation process and installed libraries once. 

_**If you want further info or remote access like anydesk contact  **_

**Comment by Mohammadkhan18** [comment]
Thank you I have figure out the issue and able to solve the issue
You can close the issue in GitHub

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
